### ISSUE TITLE
Typo in the cookbook.

### ISSUE THREAD

**Issue by sfontes** [ZCA/zenoss-chef-cookbook#11]
undefined method `error' for Chef:Class 
/var/chef-solo/cookbooks/zenoss/recipes/server.rb:26:in`from_file'

26>>   Chef::log.error("You have not accepted the Java License Agreement" +

**Comment by dpetzel** [comment]
Should be good to go via your self supplied fix (thanks again for the PR). 358515341abae7565125b38e94cc9a2d30d0a721
