### ISSUE TITLE
Mail server library conflict on CentOS and RHEL 6

### ISSUE THREAD

**Issue by sfiggins** [ZCA/zenoss-chef-cookbook#15]
The postfix package depends on a mysql library that is purged by the Zenoss MySQL install.   As a result there is no email server on the node after applying this cookbook and you can't install postfix.   

I've read that this can be resolved by also installing the shared-compat rpm:

MySQL-shared-compat-5.5.28-1.el6.x86_64.rpm

I haven't been able to test that yet as I get download errors whenever I try to retrieve that file.  I still want to log this in case anyone else is wondering what happened to the mail server on their system.

**Comment by sfiggins** [comment]
I was able to retrieve the MySQL-shared-compat rpm from http://downloads.skysql.com/archive/index/p/mysql/v/5.5.28 and can confirm that it allowed me to reinstall postfix.  It might be a good idea to include this file with the other RPMs installed.   Though we might first need to get downloads.mysql.com to fix the problem preventing download.   We might also want to warn people using Cent/Rhel that installing MySQL with this recipe will probably uninstall their postfix.

**Comment by sfiggins** [comment]
I can report that while I have the download problem with the shared-compat rpm from 5.5.28  I don't have a problem with 5.5.31, so using a later release might make things easier than trying to get mysql to fix the broken file in their archive.

**Comment by dpetzel** [comment]
I just started looking at this, and I'm not yet sure what the best path forward is. Based on https://github.com/zenoss/core-autodeploy/blob/4.2.5/core-autodeploy.sh#L161 5.28 seems to be the preferred version
