### ISSUE TITLE
rpm_file is nil when rpm_url attribute is set. 

### ISSUE THREAD

**Issue by sfiggins** [ZCA/zenoss-chef-cookbook#19]
If you set ['zenoss']['core4']['rpm_url'] to a custom url, then line 63 of core4.rb will fail.  rpm_file's value will be nil.

**Comment by dpetzel** [comment]
@sfiggins just to confirm, this fix was included in your recent pull request and this can be closed correct?

**Comment by sfiggins** [comment]
Correct.  This can be closed.
